[package]
name = "first_scarb_project"
version = "0.1.0"
edition = "2024_07"

[cairo]
enable-gas = false

[dependencies]
cairo_execute = "2.15.1"


[[target.executable]]
function = "first_scarb_project::main"
